version: '3'

services:
  nginx-rtmp:
    build: .
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ./certs:/opt/certs
  nvenc-test:
    build: .
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    command: |
      ffmpeg -i - -c:v h264_nvenc -profile high444p -pixel_format yuv444p -preset default output.mp4
